apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fun-facts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Metodil/u34-fun-facts.git'
    targetRevision: HEAD
    path: kubernetes
  destination:
    namespace: fun-facts
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - Validate=false
      - CreateNamespace=true
