repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-merge-conflict
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0  # Specify the desired version of Gitleaks
    hooks:
      - id: gitleaks
#-  repo: https://github.com/bridgecrewio/checkov.git
#   rev: '' # change to tag or sha
#   hooks:
#    - id: checkov
#    - id: checkov_container
#    - id: checkov_diff
#    - id: checkov_diff_container
#    - id: checkov_secrets
#    - id: checkov_secrets_container
