apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: FunFacts
    role: generator
  name: generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: FunFacts
      role: generator
  template:
    metadata:
      labels:
        app: FunFacts
        role: generator
    spec:
      containers:
        - env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: config-fun-facts-env
                key: DB_HOST
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: config-fun-facts-env
                key: DB_NAME
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: secret-fun-facts
                key: DB_PASS
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: secret-fun-facts
                key: DB_USER
          image: metodil/u34-fun-facts-generator:latest
          name: con-generator
          resources:
            limits:
              memory: "256Mi"  # Maximum memory allowed
              cpu: "200m"       # Maximum CPU allowed (200 milliCPU)
            requests:
              memory: "128Mi"  # Initial memory request
              cpu: "100m"       # Initial CPU request
      restartPolicy: Always
