apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app-vars.yaml
- generator-deployment.yaml
- storage-deployment.yaml
- storage-svc.yaml
- web-deployment.yaml
- web-svc.yaml
images:
- name: metodil/u34-fun-facts-generator
  newName: metodil/u34-fun-facts-generator
  newTag: 423e45581f7ea075bb7f67d8b5983cbb53d8cf7f
- name: metodil/u34-fun-facts-storage
  newName: metodil/u34-fun-facts-storage
  newTag: 423e45581f7ea075bb7f67d8b5983cbb53d8cf7f
- name: metodil/u34-fun-facts-web
  newName: metodil/u34-fun-facts-web
  newTag: 423e45581f7ea075bb7f67d8b5983cbb53d8cf7f
