apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app-vars.yaml
- generator-deployment.yaml
- storage-deployment.yaml
- storage-svc.yaml
- web-deployment.yaml
- web-svc.yaml
images:
- name: klimentchakarovski/projecti
  newName: klimentchakarovski/projecti
  newTag: 9261a456b0f4d8f67af539987269e2cfd2990bae
