apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app-vars.yaml
- generator-deployment.yaml
- storage-deployment.yaml
- storage-svc.yaml
- web-deployment.yaml
- web-svc.yaml
images:
- name: metodil/u34-fun-facts-generator
  newName: metodil/u34-fun-facts-generator
  newTag: 6621b145539dcf4cf1d1cde557f22c09a975d743
- name: metodil/u34-fun-facts-storage
  newName: metodil/u34-fun-facts-storage
  newTag: 6621b145539dcf4cf1d1cde557f22c09a975d743
- name: metodil/u34-fun-facts-web
  newName: metodil/u34-fun-facts-web
  newTag: 6621b145539dcf4cf1d1cde557f22c09a975d743
