apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app-vars.yaml
- generator-deployment.yaml
- storage-deployment.yaml
- storage-svc.yaml
- web-deployment.yaml
- web-svc.yaml
images:
- name: metodil/u34-fun-facts-generator
  newName: metodil/u34-fun-facts-generator
  newTag: db72a7bcbba0b388116cece2363e64c250a586cb
- name: metodil/u34-fun-facts-storage
  newName: metodil/u34-fun-facts-storage
  newTag: db72a7bcbba0b388116cece2363e64c250a586cb
- name: metodil/u34-fun-facts-web
  newName: metodil/u34-fun-facts-web
  newTag: db72a7bcbba0b388116cece2363e64c250a586cb
