apiVersion: v1
kind: Service
metadata:
  labels:
    app: FunFacts
    role: storage
  name: con-storage
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    app: FunFacts
    role: storage
