apiVersion: v1
kind: Service
metadata:
  labels:
    app: FunFacts
    role: storage
  name: con-storage
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: FunFacts
    role: storage
