apiVersion: v1
kind: Service
metadata:
  labels:
    app: FunFacts
    role: web
  name: con-web
spec:
  ports:
    - name: "8080"
      port: 8090
      targetPort: 5000
  selector:
    app: FunFacts
    role: web
