name: CICD-TF-common
run-name: u34 CICD-Terraform-common run on ${{ github.event_name }} event
on:
#  pull_request:
#    types:
#      - opened
#      - closed
  push:
#    branches:
#      - 'main'
    paths:
      - 'terraform/aws_common/**'
#      - '.github/workflows/tf-common.yml'
#  schedule:
#    - cron: '0 0 * * 1,4' # on Monday (1) and Thursday (4)
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_REGION: "eu-central-1"
  TF_ROOT: "terraform/aws_common"
  GITHUB_NAME: "metodil/u34-fun-facts"
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_TF_INFRA_AWS }}
  INFRACOST_SLACK_MESSAGE: "/tmp/infracost-common-slack-message.json"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Start notification CICD-TF-common
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"CICD-TF-common: started "}' $SLACK_WEBHOOK_URL

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.1.1

      - name: Terraform Init
        id: init
        run: |
          cd ${{ env.TF_ROOT }}
          terraform init

      - name: Format Terraform Code
        run: |
          cd ${{ env.TF_ROOT }}
          terraform fmt -check -diff || exit 0

      - name: Terraform Validate
        id: validate
        run: |
          cd ${{ env.TF_ROOT }}
          terraform validate

      - name: Checks notification
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"CICD-TF-common: checks is finished "}' $SLACK_WEBHOOK_URL

      - name: Install Checkov with pip
        run: pip install checkov

      - name: Checkov Scan
        id: checkov
        run: |
          cd ${{ env.TF_ROOT }}
          checkov -d . || exit 0

      - name: Security notification
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"CICD-TF-common: Security with Checkov is finished "}' $SLACK_WEBHOOK_URL

      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate Infracost cost estimate baseline
        run: |
          infracost breakdown --path=${TF_ROOT} \
                              --format=json \
                              --out-file=/tmp/infracost-common.json

      - name: Post Infracost comment
        run: |
            touch grype.yaml
            infracost comment github --path=/tmp/infracost-common.json \
                                     --repo=${{ env.GITHUB_NAME }} \
                                     --github-token=${{ secrets.U34_FP_GITHUB_TOKEN }} \
                                     --behavior=hide-and-new \
                                     --commit=${{ github.sha }}
#                                     --pr=${{ github.event.pull_request.number }}

      - name: Post Infracost comment
        run: |
          touch ${{ env.INFRACOST_SLACK_MESSAGE }}
          infracost output  --path=/tmp/infracost-common.json \
                            --format slack-message \
                            --out-file ${{ env.INFRACOST_SLACK_MESSAGE }}

      - name: cURL to send a Slack message via a webhook
        run: |
          curl -X POST -H "Content-type: application/json" --data @${{ env.INFRACOST_SLACK_MESSAGE }} $SLACK_WEBHOOK_URL

      - name: Terraform Plan
        id: plan
        run: |
          cd ${{ env.TF_ROOT }}
          terraform plan -out=tfplan-common -detailed-exitcode
          echo "TF_EXIT_CODE=$?" >> $GITHUB_ENV

      - name: Terraform Plan notification
        run: |
          if [ "$TF_EXIT_CODE" -eq 0 ]; then
            echo "✅ No changes detected."
            curl -X POST -H 'Content-type: application/json' --data '{"text":"CICD-TF-common: ✅ No changes detected. Your infrastructure matches the configuration. "}' $SLACK_WEBHOOK_URL
          elif [ "$TF_EXIT_CODE" -eq 2 ]; then
            echo "⚠️ Changes detected in Terraform plan."
            curl -X POST -H 'Content-type: application/json' --data '{"text":"CICD-TF-common: ⚠️ Changes detected in Terraform plan. Running aplly. "}' $SLACK_WEBHOOK_URL
          fi

      - name: Terraform Apply if changes detected
        run: |
          #if [ "$TF_EXIT_CODE" -eq 2 ]; then
            cd ${{ env.TF_ROOT }}
            terraform apply --auto-approve tfplan-common
            curl -X POST -H 'Content-type: application/json' --data '{"text":"CICD-TF-common: Terraform apply finsh. "}' $SLACK_WEBHOOK_URL
          #fi
