name: CICD-TF-EKS-apply
run-name: u34 CICD-Terraform-EKS-apply run on ${{ github.event_name }} event
on:
  workflow_dispatch:
#    push:
#        paths:
#          - '.github/workflows/tf-eks-apply.yml'
#    push:
#      branches: [main]
#    pull_request:
#      branches: [main]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_REGION: "eu-central-1"
  TF_S3_NAME: "u34-tfstate"
  TF_PLAN_NAME: "tfplan-eks"
  TF_ROOT: "terraform/aws_eks"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.1.1

      - name: Terraform Init
        id: init
        run: |
          cd ${{ env.TF_ROOT }}
          terraform init

      - name: Copy tfplan from the S3 Bucket
        run: |
          cd ${{ env.TF_ROOT }}
          aws s3 cp s3://u34-tfstate/tfplan-eks tfplan-eks

      - name: Terraform Apply
        id: apply
        run: |
          cd ${{ env.TF_ROOT }}
          terraform apply --auto-approve tfplan-eks
