name: CICD-Terraform-vault-destroy
run-name: u34 CICD-Terraform-vault-destroy run only manual
on:
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_REGION: "eu-central-1"
  TF_S3_NAME: "u34-tfstate"
  TF_PLAN_NAME: "tfplan-vault-destroy"
  TF_ROOT: "terraform/aws_vault"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.1.1

      - name: Terraform Init
        id: init
        run: |
          cd ${{ env.TF_ROOT }}
          terraform init

#      - uses: trstringer/manual-approval@v1
#        with:
#          secret: ${{ github.TOKEN }}
#          approvers: metodil
#          minimum-approvals: 1
#          issue-title: "Destroy Vault EC2 instance"
#          issue-body: "Please approve or deny the destroy Vault instance"
#          exclude-workflow-initiator-as-approver: false
##          Approval keywords - "approve", "approved", "lgtm", "yes"
##          Denied keywords - "deny", "denied", "no"
#          additional-approved-words: ''
#          additional-denied-words: ''


      - name: Terraform Destroy Vault
        id: apply
        run: |
          cd ${{ env.TF_ROOT }}
          terraform plan -destroy -out=${{ env.TF_PLAN_NAME }}
          terraform apply ${{ env.TF_PLAN_NAME }}
